### ISSUE TITLE
Implement new Route item component

### ISSUE THREAD

**Issue by jfschwarz** [gnosisguild/zodiac-pilot#116]
Implement the `<RouteItem>` component based on this mock-up: https://www.figma.com/design/dVyATiS3RwYw3S2PrHPyX3/PIlot---Smart-Connection?node-id=36-82803&t=fdRvCXqpCBUvjBWT-4

Some remarks on nomenclature, since names might be a bit confusing after the recent refactoring introducing the new routes data model:

- What used to be called a "Connection" is now a "Route". In the codebase you might still found some remnants with the old name. We can fix these as we encounter them.
- The original `Connection` TypeScript interface is still around, now called `LegacyConnection` 
- For the interim, there is an `asLegacyConnection(route)` function that turns routes into legacy connections for components that have not yet been updated to operate on the new routes data model
- To complete the confusion the `Route` type has `waypoints`, which have a `connection` property. 😅 This property is unrelated to the Pilot legacy connection, but identifies how the route waypoint is connected to the previous waypoint.

#### Side quest

The current `<RouteItem>` component uses react-moment for rendering the last used time. Let's get rid of this heavy dependency and use the native [Intl.RelativeDateFormat](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/RelativeTimeFormat) API instead.

**Comment by frontendphil** [comment]
I'm closing this because so much has changed since July.
