### ISSUE TITLE
Unable to connect to StakeWise app in Gnosis Chain

### ISSUE THREAD

**Issue by nledo** [gnosisguild/zodiac-pilot#153]
**Describe the bug**
When trying to connect to the [StakeWise app](https://app.stakewise.io/), the Pilot Extension seems unable to establish a connection and remains stuck loading without success.

**To Reproduce**

1. Go to https://app.stakewise.io/
2. Select Gnosis Chain to operate
3. Try to connect using any safe

**Expected behavior**
To be able to connect to the app.

**Comment by jfschwarz** [comment]
I cannot reproduce this @nledo. I think we've fixed connection to StakeWise in https://github.com/gnosisguild/zodiac-pilot/releases/tag/v2.14.1. Can you confirm the issue is still happening for you on that latest version?
