### ISSUE TITLE
Unable to connect to Swapr app

### ISSUE THREAD

**Issue by nledo** [gnosisguild/zodiac-pilot#154]
**Describe the bug**
When trying to connect to the [Swapr app](https://v3.swapr.eth.limo/#/swap), the Pilot Extension seems unable to establish a connection and remains stuck loading without success.

**To Reproduce**

1. Go to https://v3.swapr.eth.limo/#/swap
2. Try to connect using any safe

**Expected behavior**
To be able to connect to the app.

**Comment by frontendphil** [comment]
Hey @nledo, we looked at this issue and found a possible solution in the `swapr-algebra-ui` codebase. I've opened a PR that is linked to this issue.

**Comment by nledo** [comment]
Hey @frontendphil! Thank you! I’ll try to reach out to someone who can help us move this forward!

**Comment by frontendphil** [comment]
The PR has been merged, and a quick test on my end shows that it is now possible to use Swapr with Zodiac Pilot. Let us know if you encounter more trouble :)

**Comment by nledo** [comment]
Great @frontendphil! Everything seems to be working smoothly! Thank you!
