### ISSUE TITLE
Blank screen and console errors when opening Pilot

### ISSUE THREAD

**Issue by samepant** [gnosisguild/zodiac-pilot#156]
**Describe the bug**
When i click the Pilot extension icon, i get a blank screen and a couple console errors about multisend bad data
<img width="1480" alt="Screenshot 2024-10-08 at 11 43 24 AM" src="https://github.com/user-attachments/assets/094f5c29-6ae6-4cf3-ae8f-ab808a34ea4c">

- Chrome
- Pilot 2.14.0

**Additional context**
This could be caused by old connections i have saved in my pilot?

**Comment by jfschwarz** [comment]
Yes, probably some edge case around legacy connection migration. The quickest solution would be clearing pilot.gnosisguild.org app data.

Since I don't plan to carry over legacy connections to the next major Pilot version, I'd not investigate this issue further.
