### ISSUE TITLE
Extension can't be installed on Windows

### ISSUE THREAD

**Issue by jfschwarz** [gnosisguild/zodiac-pilot#350]
@nledo reports that the extension cannot be installed on windows anymore, starting since v3.0.0.

Windows Defender gives a virus warning and immediately deletes the zodiac-pilot.zip when downloaded from our releases page. It even blocks installs through the Chrome Webstore

**Comment by frontendphil** [comment]
@jfschwarz or @nledo, can you provide more information? Which browser was used on Windows? Chrome or Edge? Which version of Windows are we talking about? I'm currently running Windows 11 Pro and can install the extension without issues in both Edge and Chrome.

**Comment by frontendphil** [comment]
Also a targeted scan of just our files yields no threat detections with an up-to-date definition library...

**Comment by nledo** [comment]
Hey @frontendphil!
Last Friday, Windows Security mysteriously deleted the zodiac.zip file every time I tried downloading it. I also attempted to install the extension directly from the Chrome Store multiple times, but the result was the same—it kept being deleted.
Interestingly, it’s working now, but I’m not sure what might have caused the issue.

Thanks anyway!

**Comment by frontendphil** [comment]
Glad to hear that it's working now. We released 3.0.1 in the meantime, which might have fixed the root cause. Anyway, we're now also upgrading our own dependencies more regularly (and automatically) to avoid these kinds of issues based on outdated code.
