### ISSUE TITLE
`Connect to MetaMask` is disabled 🔥🔥🔥 

### ISSUE THREAD

**Issue by jfschwarz** [gnosisguild/zodiac-pilot#381]
**Steps to reproduce:**
- Remove the extension from chrome
- Load the extension (dev build) again
- Open a fresh browser window
- Load some website, e.g. https://app.aura.finance/
- Open Pilot panel
- Edit route

**Expected behavior:**
I should be able to connect to MetaMask

**Observed behavior:**
The `Connect to MetaMask` button is disabled

**Comment by frontendphil** [comment]
I've done some refactoring around all of that in https://github.com/gnosisguild/zodiac-pilot/pull/380, and I can't reproduce this behavior locally. @jfschwarz, can you check whether you can still reproduce this on the latest `main`?
