### ISSUE TITLE
Remove the need for an active route at all times

### ISSUE THREAD

**Issue by frontendphil** [gnosisguild/zodiac-pilot#389]
Currently, we require a route to be active, even to see the list of routes and/or edit a route. However, this restriction is rather arbitrary and should be removed.

## Issues

- [ ] When you launch another route from the list of routes, you might need to **clear transactions**. This currently also means deleting the current `fork.` However, that requires the current provider, which requires the currently active route. We'd need to figure out a way to circumvent this requirement
  - Instead of clearing the transactions directly, we could redirect to another route in between (e.g., `/:activeRouteId/clear-transactions/:newActiveRouteId`) that could require the active route and provider context (because it actually needs it) and then redirect from this page to `/:activeRouteId/transactions`

**Comment by jfschwarz** [comment]
>  This currently also means deleting the current fork. 

Actually, since our forks are powered by Tenderly's virtual testnets and they don't offer an API to delete these, we currently don't delete anything. So this might no longer be required at all.
